# Generated by Django 5.0.6 on 2025-12-05 13:08

import django.db.models.deletion
import django.utils.timezone
import immo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('property_type', models.CharField(choices=[('APPARTEMENT_LOCATION', 'Appartement en location'), ('APPARTEMENT_MEUBLE', 'Appartement meublé'), ('STUDIO_LOCATION', 'Studio en location'), ('STUDIO_MEUBLE', 'Studio meublé'), ('CHAMBRE_LOCATION', 'Chambre en location'), ('CHAMBRE_MEUBLE', 'Chambre meublée'), ('MAGASIN', 'Magasin'), ('IMMEUBLE', 'Immeuble')], max_length=40)),
                ('listing_status', models.CharField(choices=[('LOCATION', 'À louer'), ('VENTE', 'À vendre')], default='LOCATION', max_length=20)),
                ('furnished', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('CLOSED', 'Terminé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='immo.bien')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=immo.models.report_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='immo.bien')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=immo.models.message_upload_to)),
                ('kind', models.CharField(choices=[('TEXTE', 'Message'), ('DEVIS', 'Devis'), ('PREUVE', "Preuve d'intervention")], default='TEXTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('LATE', 'Retard')], default='PENDING', max_length=20)),
                ('payment_type', models.CharField(choices=[('LOYER', 'Loyer'), ('RESERVATION', 'Réservation'), ('PRESTATAIRE', 'Prestataire')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='immo.bien')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='immo.contract')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestataireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataires', to='immo.bien')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bien', 'prestataire')},
            },
        ),
    ]
