# Generated by Django 5.2.2 on 2025-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='property_type',
            field=models.CharField(choices=[('APPARTEMENT_LOCATION', 'Appartement en location'), ('APPARTEMENT_MEUBLE', 'Appartement meublé'), ('STUDIO_LOCATION', 'Studio en location'), ('STUDIO_MEUBLE', 'Studio meublé'), ('CHAMBRE_LOCATION', 'Chambre en location'), ('CHAMBRE_MEUBLE', 'Chambre meublée'), ('MAGASIN', 'Magasin'), ('IMMEUBLE', 'Immeuble'), ('MAISON', 'Maison')], max_length=40),
        ),
    ]
