# Generated by Django 5.0.6 on 2025-12-05 13:30

import django.db.models.deletion
import immo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0002_alter_bien_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=immo.models.bien_media_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='immo.bien')),
            ],
        ),
    ]
